// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjipeimokpdnwsuphhci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqaXBlaW1va3BkbndzdXBoaGNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDg1ODEsImV4cCI6MjA2NjE4NDU4MX0.OVREqLz1eOoCo85UnVZ0pgesfVrr_DD1OH3da04mpeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);